PiFinale/src/ProjetBundle/Entity/Reclammation.php
<?php

namespace ProjetBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Competence
 *
 * @ORM\Table(name="Reclamtion", indexes={@ORM\Index(name="id_user", columns={"id_user"})})
 * @ORM\Entity
 */
class Reclammation
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var \FosUser
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_user", referencedColumnName="id")
     * })
     */
    private $id_user;

    /**
     * @var string
     *
     * @ORM\Column(name="objet", type="string", length=255, nullable=false)
     */
    private $objet;

    /**
     * @var string
     *
     * @ORM\Column(name="message", type="string", length=255, nullable=false)
     */
    private $message;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="date", nullable=true)
     */
    private $date;

    /**
     * @var string
     *
     * @ORM\Column(name="etat", type="string", length=255, nullable=false)
     */
    private $etat;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return \FosUser
     */
    public function getIdUser()
    {
        return $this->id_user;
    }

    /**
     * @param \FosUser $id_user
     */
    public function setIdUser($id_user)
    {
        $this->id_user = $id_user;
    }

    /**
     * @return string
     */
    public function getObjet()
    {
        return $this->objet;
    }

    /**
     * @param string $objet
     */
    public function setObjet($objet)
    {
        $this->objet = $objet;
    }

    /**
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * @param string $message
     */
    public function setMessage($message)
    {
        $this->message = $message;
    }

    /**
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param \DateTime $date
     */
    public function setDate($date)
    {
        $this->date = $date;
    }

    /**
     * @return string
     */
    public function getEtat()
    {
        return $this->etat;
    }

    /**
     * @param string $etat
     */
    public function setEtat($etat)
    {
        $this->etat = $etat;
    }





}

PiFinale/src/ProjetBundle/Controller/DefaultController.php
<?php

namespace ProjetBundle\Controller;
use FOS\UserBundle\Model\User as BaseUser ;
use ProjetBundle\Entity\Candidature;
use ProjetBundle\Entity\Publication;
use ProjetBundle\Entity\User ;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    public function indexAction(Request $request)
    {
        $posts = $this -> getDoctrine()->getRepository('ProjetBundle:Publication')->findAll();
        $post  = $this->get('knp_paginator')->paginate(
            $posts,
            $request->query->get('page', 1)/*le numéro de la page à afficher*/,
            3/*nbre d'éléments par page*/
        );
        return $this->render('@Projet/Default/Index.html.twig',['posts'=> $post]
        );

    }
    public function appAction(Publication $publication)
    {
        $user = $this->get('security.token_storage')->getToken()->getuser() ;
        $candidature = new Candidature();
        $candidature -> setIdFreelancer($user);
        $candidature -> setIdProjet($publication);
        $candidature -> setDate(new \DateTime('now'));
        $candidature -> setEtat('non traite');

        $em = $this->getDoctrine()->getManager();

        $em->persist($candidature);
        $em->flush();

        $posts = $this -> getDoctrine()->getRepository('ProjetBundle:Publication')->findAll();
        return $this->render('@Projet/Default/Index.html.twig',['posts'=> $posts]
        );

    }



}

PiFinale/src/ProjetBundle/Resources/views/Default/admin/ModifierFormation.html.twig
{% extends 'base2.html.twig' %}
{% block cont %}

    <div class="col-md-12">
        <div class="card card-block">

            {{ form_start(form) }}
            <div class="form-group">

                {{ form_widget(form.imag,{'attr':{'class':'form-control custom-select'}} ) }}
            </div>
            <div class="form-group">
                <label>Titre  </label>

                {{ form_widget(form.nom,{'attr':{'class':'form-control'}} ) }}
            </div>
            <div class="form-group">
                <label>Url  </label>
                {{ form_widget(form.url1,{'attr':{'class':'form-control'}} ) }}
            </div>


            <div class="form-group">
                <label>description</label>

                {{ form_widget(form.descr, { 'attr': {

                    'rows' : '25',
                    'cols' : '250',
                    'class':'form-control',
                    'maxlength' : '200'}} ) }}
            </div>

            {{ form_widget(form.Modifier)}}
            {{ form_rest(form) }}
            {{ form_end(form) }}





        </div>
    </div>



{% endblock %}

PiFinale/src/ProjetBundle/Resources/views/Default/admin/acceuill.html.twig
{% extends 'base2.html.twig' %}
{% block cont %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        {{ gc_draw([histogram,histogram1,histogram2], ['div_histogram','div_histogram1','div_histogram2']) }}
    </script>

        <!-- Column -->
    <div class="col-md-3 col-lg-3 col-xlg-3">
            <div class="card card-inverse card-info">
                <div class="box bg-info text-center">
                    <h1 class="font-light text-white">{{ nbr.contrats }}</h1>
                    <h6 class="text-white">Contrats Acceptés </h6>
                </div>
            </div>
        </div>
        <!-- Column -->
    <div class="col-md-3 col-lg-3 col-xlg-3">
            <div class="card card-primary card-inverse">
                <div class="box text-center">
                    <h1 class="font-light text-white">{{ nbr.contartns }}</h1>
                    <h6 class="text-white">Contarts en cours </h6>
                </div>
            </div>
        </div>
        <!-- Column -->

    <div class="col-md-3 col-lg-3 col-xlg-3">
    <div class="card card-inverse card-info">
        <div class="box text-center">
            <h1 class="font-light text-white">{{ nbr.FormationS }}</h1>
            <h6 class="text-white">Formations Soft Skills</h6>
        </div>
    </div>
</div>
        <!-- Column -->
    <div class="col-md-3 col-lg-3 col-xlg-3">
            <div class="card card-inverse card-warning">
                <div class="box text-center">
                    <h1 class="font-light text-white">{{ nbr.FormationH }}</h1>
                    <h6 class="text-white">Formations Hard Skills</h6>
                </div>
            </div>
        </div>
    <div class="col-md-3 col-lg-3 col-xlg-3">
        <div class="card card-inverse card-success">
            <div class="box text-center">
                <h1 class="font-light text-white">{{ nbr.Reclammation }}</h1>
                <h6 class="text-white">Réclamations </h6>
            </div>
        </div>
    </div>

    <div class="col-md-3 col-lg-3 col-xlg-3">
        <div class="card card-primary card-inverse">
        <div class="box text-center">
            <h1 class="font-light text-white">{{ nbr.can }}</h1>
            <h6 class="text-white">Candidatures</h6>
        </div>
    </div>
</div>
    <div class="col-md-3 col-lg-3 col-xlg-3">
        <div class="card card-inverse card-success">
            <div class="box text-center">
                <h1 class="font-light text-white">{{ nbr.Pro }}</h1>
                <h6 class="text-white">Projets </h6>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-lg-3 col-xlg-3">
        <div class="card card-inverse card-warning">
            <div class="box text-center">
                <h1 class="font-light text-white">{{ nbr.Pub }}</h1>
                <h6 class="text-white">Publications</h6>
            </div>
        </div>
    </div>

    <br>
    <div class="col-md-12">


        <div class="chart" id="div_histogram1"></div>
    </div>
    <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br><br> <br><br>

    <div class="col-md-12">


        <div class="chart" id="div_histogram"></div>
    </div>
    <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br> <br><br> <br> <br><br> <br> <br><br> <br> <br> <br> <br> <br> <br> <br> <br>
    <div class="col-md-12">


        <div class="chart" id="div_histogram2"></div>
    </div>


{% endblock %}

PiFinale/src/ProjetBundle/Resources/views/Default/admin/ajouterFormation.html.twig
{% extends 'base2.html.twig' %}
{% block cont %}

        <div class="col-md-12">
            <div class="card card-block">

                    {{ form_start(form) }}
                    <div class="form-group">

                         {{ form_widget(form.imag,{'attr':{'class':'form-control custom-select'}} ) }}
                    </div>
                    <div class="form-group">
                        <label>Titre  </label>

                        {{ form_widget(form.nom,{'attr':{'class':'form-control'}} ) }}
                    </div>
                    <div class="form-group">
                        <label>Url  </label>
                        {{ form_widget(form.url1,{'attr':{'class':'form-control'}} ) }}
                    </div>


                    <div class="form-group">
                    <label>description</label>

                    {{ form_widget(form.descr, { 'attr': {

                        'rows' : '25',
                        'cols' : '250',
                        'class':'form-control',
                        'maxlength' : '200'}} ) }}
                </div>

                    {{ form_widget(form.Ajouter)}}
                {{ form_rest(form) }}
                {{ form_end(form) }}





            </div>
        </div>



{% endblock %}

PiFinale/src/ProjetBundle/Resources/views/Default/admin/ajouterQuiz.html.twig
{% extends 'base2.html.twig' %}
{% block cont %}

    <div class="col-md-12">
        <div class="card card-block">

            {{ form_start(form) }}
            <div class="form-group">

                {{ form_widget(form.idF,{'attr':{'class':'form-control custom-select'}} ) }}
            </div>
            <div class="form-group">
                <label>question  </label>

                {{ form_widget(form.qes,{'attr':{'class':'form-control'}} ) }}
            </div>



            <div class="form-group">
                <label>reponse</label>

                {{ form_widget(form.reponse, { 'attr': {

                    'rows' : '25',
                    'cols' : '250',
                    'class':'form-control',
                    'maxlength' : '200'}} ) }}
            </div>

            {{ form_widget(form.Ajouter)}}
            {{ form_rest(form) }}
            {{ form_end(form) }}





        </div>
    </div>



{% endblock %}

PiFinale/src/ProjetBundle/Resources/views/Default/admin/modifierQuiz.html.twig
{% extends 'base2.html.twig' %}
{% block cont %}

    <div class="col-md-12">
        <div class="card card-block">

            {{ form_start(form) }}
            <div class="form-group">

                {{ form_widget(form.idF,{'attr':{'class':'form-control custom-select'}} ) }}
            </div>
            <div class="form-group">
                <label>qestion  </label>

                {{ form_widget(form.qes,{'attr':{'class':'form-control'}} ) }}
            </div>



            <div class="form-group">
                <label>reponse</label>

                {{ form_widget(form.reponse, { 'attr': {

                    'rows' : '25',
                    'cols' : '250',
                    'class':'form-control',
                    'maxlength' : '200'}} ) }}
            </div>

            {{ form_widget(form.Modifier)}}
            {{ form_rest(form) }}
            {{ form_end(form) }}





        </div>
    </div>



{% endblock %}

PiFinale/src/ProjetBundle/Resources/views/Default/admin/reclamtion.html.twig
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <title>Smart-Start</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{{ asset('Bundles/Pack/assets/images/logo/favicon.png') }}" >
    <!-- Bootstrap Core CSS -->
    <link href="{{ asset('Bundles/assets/plugins/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{{ asset('Bundles/admin/css/style.css')}}" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="{{ asset('Bundles/admin/css/colors/blue.css')}}" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body class="fix-header card-no-border">

<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- User profile -->
        <div class="user-profile">
            <!-- User profile image -->
            <div class="profile-img"> <img src="{{ asset('Bundles/assets/images/users/1.png')}}" alt="user" /> </div>
            <!-- User profile text-->
            <div class="profile-text"> admin

            </div>
        </div>
        <!-- End User profile text-->
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="nav-small-cap"></li>
                <li>
                    <a class="has-arrow" href="{{ path('aceuillAdmin') }}" aria-expanded="false"><i class=""></i><span class="hide-menu">Dashboard </span></a>

                </li>
                <li>
                    <a class="has-arrow" href="#" aria-expanded="false"><i class=""></i><span class="hide-menu">Formation  </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ path('ajouterFormation') }}">Ajouter Formation</a></li>
                        <li><a href="{{ path('consulterFormation') }}">Liste des formations</a></li>

                    </ul>
                </li>
                <li>
                    <a class="has-arrow" href="#" aria-expanded="false"><i class=""></i><span class="hide-menu">Test  </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ path('ajouterquiz') }}">Ajouter quiz</a></li>
                        <li><a href="{{ path('consulterQuiz') }}">Liste des quizs</a></li>

                    </ul>
                </li>
                <li>
                    <a class="has-arrow" href="{{ path('Reclamtionadmin') }}" aria-expanded="false"><i class=""></i><span class="hide-menu">Reclamtion </span></a>

                </li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
    <!-- Bottom points-->
    <div class="sidebar-footer">

        <a href="{{ path('fos_user_security_logout') }}" class="link" data-toggle="tooltip" title="Logout"><i class="mdi mdi-power"></i></a>

    </div>
    <!-- End Bottom points-->
</aside><!-- ============================================================== -->
<!-- Preloader - style you can find in spinners.css -->
<!-- ============================================================== -->

<!-- ============================================================== -->
<!-- Main wrapper - style you can find in pages.scss -->
<!-- ============================================================ -->
<div id="main-wrapper">
    <!-- ============================================================== -->
    <!-- Topbar header - style you can find in pages.scss -->
    <!-- ============================================================== -->

    <!-- ============================================================== -->
    <!-- End Topbar header -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->

    <!-- ============================================================== -->
    <!-- End Left Sidebar - style you can find in sidebar.scss  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Page wrapper  -->
    <!-- ============================================================== -->
    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->

            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-block">
                            <h4 class="card-title">Liste des Reclamtions</h4>

                            <div class="table-responsive m-t-40">
                                <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                                    <thead>
                                    <tr>
                                        <th>Nom</th>
                                        <th>Objet</th>
                                        <th>Mesage</th>
                                        <th>Date</th>
                                        <th>Etat</th>
                                        <th>Action</th>

                                    </tr>
                                    </thead>
                                    <tfoot>
                                    <tr>
                                        <th>Nom</th>
                                        <th>Objet</th>
                                        <th>Mesage</th>
                                        <th>Date</th>
                                        <th>Etat</th>
                                        <th>Action</th>

                                    </tr>
                                    </tfoot>
                                    <tbody>
                                    {% for p in con %}

                                        <tr>
                                            <td>{{ p.idUser }}</td>
                                            <td>{{ p.objet }}</td>

                                                <td> {{ p.message }}</td>

                                                <td> {{ p.date|date("m/d/Y") }}</td>
                                                  <th>{{ p.etat }}</th>


                                            <td>    <button class="btn btn-warning" > <a href="{{ path('Repondre', {'id': p.id}) }}"> Repondre  </a> </button></td>
                                        </tr>

                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->

        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->

    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Page wrapper  -->
<!-- ============================================================== -->

<!-- ============================================================== -->
<!-- End Wrapper -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- All Jquery -->
<!-- ============================================================== -->
<script src="{{ asset('Bundles/assets/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap tether Core JavaScript -->
<script src="{{ asset('Bundles/assets/plugins/bootstrap/js/tether.min.js')}}"></script>
<script src="{{ asset('Bundles/assets/plugins/bootstrap/js/bootstrap.min.js')}}"></script>
<!-- slimscrollbar scrollbar JavaScript -->
<script src="{{ asset('Bundles/admin/js/jquery.slimscroll.js')}}"></script>
<!--Wave Effects -->
<script src="{{ asset('Bundles/admin/js/waves.js')}}"></script>
<!--Menu sidebar -->
<script src="{{ asset('Bundles/admin/js/sidebarmenu.js')}}"></script>
<!--stickey kit -->
<script src="{{ asset('Bundles/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js')}}"></script>
<!--Custom JavaScript -->
<script src="{{ asset('Bundles/admin/js/custom.min.js')}}"></script>
<!-- This is data table -->
<script src="{{ asset('Bundles/assets/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<!-- start - This is for export functionality only -->
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
<!-- end - This is for export functionality only -->
<script>
    $(document).ready(function() {
        $('#myTable').DataTable();
        $(document).ready(function() {
            var table = $('#example').DataTable({
                "columnDefs": [{
                    "visible": false,
                    "targets": 2
                }],
                "order": [
                    [2, 'asc']
                ],
                "displayLength": 25,
                "drawCallback": function(settings) {
                    var api = this.api();
                    var rows = api.rows({
                        page: 'current'
                    }).nodes();
                    var last = null;
                    api.column(2, {
                        page: 'current'
                    }).data().each(function(group, i) {
                        if (last !== group) {
                            $(rows).eq(i).before('<tr class="group"><td colspan="5">' + group + '</td></tr>');
                            last = group;
                        }
                    });
                }
            });
            // Order by the grouping
            $('#example tbody').on('click', 'tr.group', function() {
                var currentOrder = table.order()[0];
                if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                    table.order([2, 'desc']).draw();
                } else {
                    table.order([2, 'asc']).draw();
                }
            });
        });
    });
    $('#example23').DataTable({
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    });
</script>
<!-- ============================================================== -->
<!-- Style switcher -->
<!-- ============================================================== -->
<script src="{{ asset('Bundles/assets/plugins/styleswitcher/jQuery.style.switcher.js')}}"></script>
</body>

</html>